version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/:rw
    ports:
      - 80:80
      - 443:443
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8
    volumes:
      - ./var/mysql:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
